[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.96

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }

# Colors (Alabaster)
# author tonsky

[colors.primary]
background = '#F7F7F7'
foreground = '#434343'

[colors.cursor]
text = '#F7F7F7'
cursor = '#434343'

[colors.normal]
black = '#000000'
red = '#AA3731'
green = '#448C27'
yellow = '#CB9000'
blue = '#325CC0'
magenta = '#7A3E9D'
cyan = '#0083B2'
white = '#BBBBBB'

[colors.bright]
black = '#777777'
red = '#F05050'
green = '#60CB00'
yellow = '#FFBC5D'
blue = '#007ACC'
magenta = '#E64CE6'
cyan = '#00AACB'
white = '#FFFFFF'

# Tokyo Night Storm
#[colors.bright]
#black = "#444b6a"
#blue = "#7da6ff"
#cyan = "#0db9d7"
#green = "#b9f27c"
#magenta = "#bb9af7"
#red = "#ff7a93"
#white = "#acb0d0"
#yellow = "#ff9e64"
#
#[colors.normal]
#black = "#32344a"
#blue = "#7aa2f7"
#cyan = "#449dab"
#green = "#9ece6a"
#magenta = "#ad8ee6"
#red = "#f7768e"
#white = "#9699a8"
#yellow = "#e0af68"
#
#[colors.primary]
#background = "#24283b"
#foreground = "#a9b1d6"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
